"""add invite code

Revision ID: 02e1eb232e46
Revises: e4706f4af10a
Create Date: 2026-07-12 15:51:37.685001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e1eb232e46'
down_revision: Union[str, Sequence[str], None] = 'e4706f4af10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('invite_code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'groups', ['invite_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_column('groups', 'invite_code')
    # ### end Alembic commands ###
