"""add receipt url to expenses

Revision ID: ff8ea26c7538
Revises: fe4112eed348
Create Date: 2026-08-28 10:24:19.750353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ff8ea26c7538'
down_revision: Union[str, Sequence[str], None] = 'fe4112eed348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('receipt_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('settlements', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settlements', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('expenses', 'receipt_url')
    # ### end Alembic commands ###
